# DO NOT EDIT:
# This file is generated by tools/export_map_projection.py.
from dcs.terrain.projections import TransverseMercator

PARAMETERS = TransverseMercator(
    central_meridian=21,
    false_easting=-62702.00000000087,
    false_northing=-7543624.999999979,
    scale_factor=0.9996,
)
