# DO NOT EDIT:
# This file is generated by tools/export_map_projection.py.
from dcs.terrain.projections import TransverseMercator

PARAMETERS = TransverseMercator(
    central_meridian=21,
    false_easting=35427.619999985734,
    false_northing=-6061633.128000011,
    scale_factor=0.9996,
)
